# Generated by Django 6.1.1 on 2026-09-28 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_reward_cost_points_alter_userprofile_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizattempt',
            old_name='score',
            new_name='balance_change',
        ),
        migrations.AddField(
            model_name='question',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='correct_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='finish_reason',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'Ukończony'), ('QUIZ_TIMEOUT', 'Przekroczono czas quizu')], max_length=30),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='incorrect_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='is_rewarded_attempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='point_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='total_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reward',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='cost_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
