# Generated by Django 6.1.1 on 2026-09-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_score_quizattempt_balance_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Ważna do'),
        ),
    ]
