# Generated by Django 6.1.1 on 2026-09-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_reward_valid_until'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='reward',
            name='delivery_method',
            field=models.CharField(choices=[('EMAIL', 'Nagroda cyfrowa - e-mail'), ('SHIPPING', 'Nagroda fizyczna - wysyłka')], default='EMAIL', max_length=20, verbose_name='Sposób przekazania'),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='delivery_method',
            field=models.CharField(choices=[('EMAIL', 'Nagroda cyfrowa - e-mail'), ('SHIPPING', 'Nagroda fizyczna - wysyłka')], default='EMAIL', max_length=20),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='redemption_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='shipping_address_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='shipping_apartment_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='shipping_country',
            field=models.CharField(blank=True, default='Polska', max_length=100),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='shipping_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='shipping_house_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='shipping_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='shipping_street',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='status',
            field=models.CharField(choices=[('EMAIL_PENDING', 'Oczekuje na wysłanie e-maila'), ('SENT', 'Wysłana e-mailem'), ('EMAIL_FAILED', 'Błąd wysyłki e-maila'), ('ADDRESS_REQUIRED', 'Oczekuje na adres'), ('READY_TO_SHIP', 'Gotowa do wysyłki'), ('SHIPPED', 'Wysłana')], default='EMAIL_PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
