# Generated by Django 6.1.1 on 2026-09-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_question_options_reward_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ważny do'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='current_question_index',
            field=models.PositiveIntegerField(default=0, verbose_name='Aktualny numer pytania'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='current_question_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Czas rozpoczęcia aktualnego pytania'),
        ),
    ]
